[package]
name = "jta-display-wall-adapter-code-generation"
version = "0.0.0"
authors = ["jonas-kell"]
repository = "https://github.com/jonas-kell/jta-display-wall-adapter"
edition = "2021"

[dependencies]
rust_to_ts_types = { path = "./rust_to_ts_types" }